/**
 * @hdclog_com.h
 *
 * Copyright (c) Huawei Technologies Co., Ltd. 2018-2019. All rights reserved.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

#ifndef HDCLOG_COM_H
#define HDCLOG_COM_H

typedef enum {
    HDCLOG_SUCCESSED = 0,
    HDCLOG_MALLOC_FAILED = 1,
    HDCLOG_CLIENT_CREATE_FAILED = 2,
    HDCLOG_SESSION_CREATE_FAILED = 3,
    HDCLOG_SESSION_RELEASE_FAILED = 4,
    HDCLOG_CLIENT_RELEASE_FAILED = 5,
    HDCLOG_WRITE_CMD_DATA2GLOBAL_FAILED = 6,
    HDCLOG_MULTI_THREAD_CREATE_FAILED = 7,
    HDCLOG_WRITE_FAILED = 8,
    HDCLOG_DEVICE_READ_DATA_FAILED = 9,
    HDCLOG_INIT_FAILED = 10,
    HDCLOG_FULL_QUEUE = 11,
    HDCLOG_EMPTY_QUEUE = 12,
    HDCLOG_CREATE_SHARE_MEMORY_FAILED = 13,
    HDCLOG_DELETE_SHARE_MEMORY_FAILED = 14,
    HDCLOG_IS_FULL = 15,
    HDCLOG_INIT_SUCCESSED = 16,
    HDCLOG_EMPTY_NODE = 17,
    HDCLOG_NO_CREAT_SESSION = 18,
    HDCLOG_INVALID_PARAM = 19,
    HDCLOG_MSGQUEUE_RECV_FAILED = 20,
    HDCLOG_MSGQUEUE_SEND_FAILED = 21,
    HDCLOG_MSGQUEUE_GET_FAILED = 22,
    HDCLOG_SETTING_LEVEL_FAILED = 23,
    HDCLOG_MUTEX_INIT_FAILED = 24,
    HDCLOG_MUTEX_DESTROY_FAILED = 25,
    HDCLOG_COMPUTE_POWER_GROUP = 26,
    HDCLOG_IDE_GET_EVN_OR_VFID_FAILED = 27,
    HDCLOG_RESERVED
} HdclogErr;

#endif  // __HDCLOG_DEVICE_COM_H__
